; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2 on 2026-10-03 at 17:06:34
; total layer number: 150
; filament_density: 1.22
; filament_diameter: 1.75
; max_z_height: 30.00
; filament: 1
; HEADER_BLOCK_END
; filament used [mm] = 1779.21
; filament used [cm3] = 4.28
; filament used [g] = 5.22
; total filament used [g] = 5.22
; total filament cost = 0.22
; total layers count = 150
; estimated printing time (normal mode) = 38m 34s
; estimated first layer printing time (normal mode) = 0.983079s
; CONFIG_BLOCK_START
; bottom_shell_layers = 3
; cool_plate_temp = 30
; curr_bed_type = Textured PEI Plate
; default_jerk = 9
; enable_support = 0
; eng_plate_temp = 30
; hot_plate_temp = 35
; initial_layer_print_height = 0.2
; layer_height = 0.2
; nozzle_diameter = 0.4
; nozzle_temperature = 230
; outer_wall_speed = 25
; sparse_infill_density = 15%
; sparse_infill_pattern = crosshatch
; textured_plate_temp = 35
; top_shell_layers = 4
; wall_loops = 3
; CONFIG_BLOCK_END
