; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2 on 2026-10-03 at 17:06:35
; model printing time: 26m 4s; total estimated time: 32m 21s
; estimated first layer printing time (normal mode) = 6m 17s
; total layer number: 150
; model label id: 14
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 30.00
; filament: 1
; HEADER_BLOCK_END

; filament used [mm] = 1629.35
; filament used [cm3] = 3.92
; filament used [g] = 4.86
