"""The OrcaSlicer CLI adapter: command line, process control, output collection and estimate parsing.

Proven behaviour of the OrcaSlicer 2.4.2 CLI (macOS universal build, 2026-10-03; see README "Slicing"):

* ``--slice 0 --outputdir D`` writes plain G-code to ``D/plate_1.gcode`` — that is the Klipper output; no
  3MF is needed. If a future CLI only wrote a 3MF, ``Metadata/plate_1.gcode`` is extracted from it.
* ``--export-3mf NAME`` (a name RELATIVE to ``--outputdir``) additionally writes a sliced 3MF whose
  ``Metadata/plate_1.gcode`` (+ ``.md5``) and ``Metadata/slice_info.config`` are what Bambu printers print
  — that is the Bambu output (``.gcode.3mf``).
* Loose profile files must be flattened (the CLI does not resolve ``inherits`` for them) and the process
  must name the printer in ``compatible_printers``; the shipped catalog does both.
* Without OpenGL (headless) the CLI skips thumbnails and says so; slicing is unaffected.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import signal
import subprocess
import time
import zipfile
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from xml.etree import ElementTree

KLIPPER_MEDIA_TYPE = "text/x-gcode"
BAMBU_MEDIA_TYPE = "model/3mf"
MODEL_SUFFIX = {"model/stl": ".stl", "model/3mf": ".3mf"}
BAMBU_FILE = "result.gcode.3mf"
LOG_TAIL_LINES = 20
VERSION_RE = re.compile(r"^OrcaSlicer-(\d+\.\d+\.\d+)")
GENERATED_RE = re.compile(r"^; generated by OrcaSlicer (\S+)")


class SlicerError(Exception):
    def __init__(self, code: str, message: str, transient: bool):
        super().__init__(message)
        self.code = code
        self.message = message
        self.transient = transient


@dataclass
class RunResult:
    returncode: int
    log_tail: list[str]
    timed_out: bool = False
    aborted: bool = False


Runner = Callable[[list[str], Path, float, Callable[[], bool]], RunResult]


@dataclass
class SliceOutput:
    path: Path
    filename: str
    media_type: str
    gcode: str
    config: dict[str, str]
    estimates: dict
    warnings: list[dict] = field(default_factory=list)
    orcaslicer_version: str | None = None


def build_command(binary: str, workdir: Path, model: Path, target: str) -> list[str]:
    out = workdir / "out"
    cmd = [
        binary,
        "--datadir",
        str(workdir / "datadir"),
        "--load-settings",
        f"{workdir / 'printer.json'};{workdir / 'process.json'}",
        "--load-filaments",
        str(workdir / "filament.json"),
        "--slice",
        "0",
        "--outputdir",
        str(out),
        "--orient",
        "0",  # keep the generator's orientation: it is part of the design
        "--arrange",
        "1",  # centre the part on the plate
    ]
    if target == "bambu_3mf":
        cmd += ["--export-3mf", BAMBU_FILE]
    cmd.append(str(model))
    return cmd


def subprocess_runner(cmd: list[str], cwd: Path, timeout: float, should_abort: Callable[[], bool]) -> RunResult:
    """Run the CLI in its own process group with a minimal environment; kill it on timeout or abort."""
    env = {"PATH": os.environ.get("PATH", "/usr/bin:/bin"), "HOME": str(cwd), "LANG": "C.UTF-8", "TMPDIR": str(cwd)}
    log_path = cwd / "slicer.log"
    with log_path.open("wb") as log:
        # The command is built by build_command from settings and job-local paths, never from request text.
        proc = subprocess.Popen(  # noqa: S603
            cmd,
            cwd=cwd,
            stdout=log,
            stderr=subprocess.STDOUT,
            env=env,
            start_new_session=True,
        )
        deadline = time.monotonic() + timeout
        timed_out = aborted = False
        while proc.poll() is None:
            if time.monotonic() > deadline:
                timed_out = True
            elif should_abort():
                aborted = True
            if timed_out or aborted:
                try:
                    os.killpg(proc.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                proc.wait()
                break
            time.sleep(0.5)
    tail = log_path.read_text(encoding="utf-8", errors="replace").splitlines()[-LOG_TAIL_LINES:]
    return RunResult(proc.returncode, tail, timed_out, aborted)


def probe_version(binary: str, timeout: float = 60) -> str:
    """The CLI's version from the first line of ``--help`` (``OrcaSlicer-2.4.2:``)."""
    try:
        done = subprocess.run(  # noqa: S603 - the configured slicer binary, no shell
            [binary, "--help"],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise SlicerError("slicer_unavailable", f"OrcaSlicer CLI not runnable: {type(exc).__name__}", True) from None
    match = VERSION_RE.match((done.stdout or "").strip())
    if not match:
        raise SlicerError("slicer_unavailable", "OrcaSlicer CLI did not report a version", True)
    return match.group(1)


def parse_duration(text: str) -> int | None:
    """'1d 2h 3m 4s' / '38m 34s' / '0.95s' -> seconds."""
    total = 0.0
    found = False
    for value, unit in re.findall(r"(\d+(?:\.\d+)?)\s*([dhms])", text):
        total += float(value) * {"d": 86400, "h": 3600, "m": 60, "s": 1}[unit]
        found = True
    return round(total) if found else None


def _sum_numbers(text: str) -> float | None:
    try:
        return round(sum(float(x) for x in text.split(",") if x.strip()), 4)
    except ValueError:
        return None


def parse_gcode_estimates(gcode: str) -> dict:
    est: dict = {}
    for line in gcode.splitlines():
        if not line.startswith(";"):
            continue
        body = line[1:].strip()
        if body.startswith("estimated printing time (normal mode) ="):
            est["print_time_s"] = parse_duration(body.split("=", 1)[1])
        elif body.startswith("model printing time:") and "total estimated time:" in body:
            est["print_time_s"] = parse_duration(body.split("total estimated time:", 1)[1])
        elif body.startswith("total filament used [g] ="):
            est["filament_g"] = _sum_numbers(body.split("=", 1)[1])
        elif body.startswith("filament used [g] =") and "filament_g" not in est:
            est["filament_g"] = _sum_numbers(body.split("=", 1)[1])
        elif body.startswith("filament used [mm] ="):
            est["filament_mm"] = _sum_numbers(body.split("=", 1)[1])
        elif body.startswith("filament used [cm3] ="):
            est["filament_cm3"] = _sum_numbers(body.split("=", 1)[1])
    return {k: v for k, v in est.items() if v is not None}


def parse_slice_info(xml_text: str) -> tuple[dict, list[dict]]:
    """``prediction`` (s) and ``weight`` (g) of plate 1, and the slicer's warnings."""
    root = ElementTree.fromstring(xml_text)  # noqa: S314 - produced by our own slicer run, bounded size
    est: dict = {}
    warnings: list[dict] = []
    plate = root.find("plate")
    if plate is not None:
        meta = {m.get("key"): m.get("value") for m in plate.findall("metadata")}
        if (meta.get("prediction") or "").isdigit():
            est["print_time_s"] = int(meta["prediction"])
        try:
            est["filament_g"] = float(meta.get("weight") or "")
        except ValueError:
            pass
        for w in plate.findall("warning"):
            warnings.append({"msg": w.get("msg"), "level": w.get("level"), "error_code": w.get("error_code")})
    return est, warnings


def collect_output(workdir: Path, target: str) -> SliceOutput:
    out = workdir / "out"
    if target == "bambu_3mf":
        path = out / BAMBU_FILE
        if not path.is_file():
            raise SlicerError("slicer_no_output", "the slicer exited cleanly but wrote no 3MF", False)
        with zipfile.ZipFile(path) as zf:
            gcode_bytes = zf.read("Metadata/plate_1.gcode")
            md5_declared = zf.read("Metadata/plate_1.gcode.md5").decode().strip().upper()
            slice_info = zf.read("Metadata/slice_info.config").decode("utf-8")
        if hashlib.md5(gcode_bytes, usedforsecurity=False).hexdigest().upper() != md5_declared:
            raise SlicerError("slicer_output_corrupt", "plate_1.gcode does not match its md5 in the 3MF", False)
        gcode = gcode_bytes.decode("utf-8", errors="replace")
        est, warnings = parse_slice_info(slice_info)
        from_gcode = parse_gcode_estimates(gcode)
        estimates = {**from_gcode, **est, "source": "slice_info.config+gcode"}
        media_type, filename = BAMBU_MEDIA_TYPE, "plate_1.gcode.3mf"
    else:
        path = out / "plate_1.gcode"
        if not path.is_file():
            packaged = sorted(out.glob("*.3mf"))
            if not packaged:
                raise SlicerError("slicer_no_output", "the slicer exited cleanly but wrote no G-code", False)
            with zipfile.ZipFile(packaged[0]) as zf:
                path.write_bytes(zf.read("Metadata/plate_1.gcode"))
        gcode = path.read_text(encoding="utf-8", errors="replace")
        estimates = {**parse_gcode_estimates(gcode), "source": "gcode"}
        warnings = []
        media_type, filename = KLIPPER_MEDIA_TYPE, "plate_1.gcode"
    from .effective import parse_config_block

    version = None
    for line in gcode.splitlines()[:5]:
        match = GENERATED_RE.match(line)
        if match:
            version = match.group(1)
            break
    return SliceOutput(
        path=path,
        filename=filename,
        media_type=media_type,
        gcode=gcode,
        config=parse_config_block(gcode),
        estimates=estimates,
        warnings=warnings,
        orcaslicer_version=version,
    )


def _result_json(workdir: Path) -> dict:
    path = workdir / "out" / "result.json"  # written by the Linux build only
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def run_slicer(
    binary: str,
    workdir: Path,
    model: Path,
    target: str,
    timeout: float,
    should_abort: Callable[[], bool],
    runner: Runner = subprocess_runner,
) -> SliceOutput:
    (workdir / "out").mkdir(parents=True, exist_ok=True)
    (workdir / "datadir").mkdir(parents=True, exist_ok=True)
    result = runner(build_command(binary, workdir, model, target), workdir, timeout, should_abort)
    if result.aborted:
        raise SlicerError("lease_lost", "the job's lease was lost while slicing; another worker owns it", True)
    if result.timed_out:
        raise SlicerError("slicer_timeout", f"slicing took longer than {int(timeout)} s", True)
    if result.returncode != 0:
        detail = _result_json(workdir)
        reason = detail.get("error_string") or (result.log_tail[-1] if result.log_tail else "no output")
        # Killed by a signal (OOM, eviction) is worth a retry; a clean non-zero exit is the slicer refusing
        # this input with these settings, which a retry would repeat.
        transient = result.returncode < 0
        raise SlicerError(
            "slicer_failed" if transient else "slicer_rejected",
            f"OrcaSlicer exited with {result.returncode}: {reason}"[:1000],
            transient,
        )
    return collect_output(workdir, target)
